name: Build and Create Release

on:
  workflow_dispatch:
    {}
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build APK
    runs-on: self-hosted  # Use the self-hosted runner

    env:
      APK_PATH: app/build/outputs/apk/debug/

    steps:
      - name: Update Perms
        shell: bash
        run: |
          echo ${{ secrets.SUDO_PASS }} | sudo -S chmod -R 776 ../Sudoku

      - name: Setting Ownership
        shell: bash
        run: |
          echo ${{ secrets.SUDO_PASS }} | sudo -S chown -R connor:connor ../Sudoku

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Create Properties File
        id: create_prop_file
        shell: bash
        run: |
          echo "sdk.dir=/home/connor/Android/Sdk" >> local.properties

      - name: Update gradlew Perms
        shell: bash
        run: |
          echo ${{ secrets.SUDO_PASS }} | sudo -S chmod 766 gradlew

      - name: Clean
        shell: bash
        run: |
          echo ${{ secrets.SUDO_PASS }} | sudo -S ./gradlew clean

      - name: Build APK
        shell: bash
        run: |
          echo ${{ secrets.SUDO_PASS }} | sudo -S ./gradlew assembleDebug

      - name: Rename APK to Sudoku.apk
        shell: bash
        run: |
          echo ${{ secrets.SUDO_PASS }} | sudo -S mv ${{ env.APK_PATH }}app-debug.apk ${{ env.APK_PATH }}Sudoku.apk

      # # Upload APK artifact
      # - name: Upload APK artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: SudokuApp
      #     path: ${{ env.APK_PATH }}Sudoku.apk

      # Create GitHub Release and upload APK to release
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.APK_PATH }}Sudoku.apk

      - name: Clean up
        if: steps.create_prop_file.outcome == 'success'
        shell: bash
        run: |
          echo ${{ secrets.SUDO_PASS }} | sudo -S rm local.properties
