name: Run Sudoku Tests

on:
  workflow_dispatch:
    {}

jobs:
  testing:
    name: Run Tests
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          lfs: false

      # - name: Update gradlew perms
      #   shell: bash
      #   run: |
      #     echo ${{ secrets.SUDO_PASS }} \
      #     sudo chmod 755 gradlew

      # - name: Run Tests
      #   shell: bash
      #   run: |
      #     echo ${{ secrets.SUDO_PASS }} \
      #     sudo ./gradlew test

      - name: Convert Results
        shell: bash
        run: |
          python3 ./Scripts/GenerateResults.py .\app\build\test-results\testReleaseUnitTest\TEST-com.example.sudoku.SudokuTest.xml

      - name: Publish Results
        if: success()
        run: npx github-actions-ctrf "/home/connor/Documents/SudokuResults/results.json"