name: Run Sudoku Tests

on:
  workflow_dispatch:
    {}

jobs:
  testing:
    name: Run Tests
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
      - name: Update Perms
        shell: bash
        run: |
          echo ${{ secrets.SUDO_PASS }} | sudo -S chmod -R 775 ../Sudoku

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          lfs: false
#
#      - name: Resync Project
#        shell: bash
#        run: |
#          sudo ./gradlew build
#
#      - name: Run Tests
#        shell: bash
#        run: |
#          sudo ./gradlew test

#      - name: Convert Results
#        shell: bash
#        run: |
#          python3 ./Scripts/GenerateResults.py "/home/connor/Documents/Runners/Sudoku/_work/Sudoku/Sudoku/app/build/test-results/testDebugUnitTest/TEST-com.example.sudoku.SudokuTest.xml"
#
#      - name: Publish Results
#        if: success()
#        run: npx github-actions-ctrf "/home/connor/Documents/SudokuResults/results.json"