name: Testing on self hosted runner

on:
  workflow_dispatch:
    {}

jobs:
  testing:
    name: Run Tests
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Run Tests
        shell: bash
        run: |
          dir
