name: Run Sudoku Tests

on:
  workflow_dispatch:
    {}

jobs:
  testing:
    name: Run Tests
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
      - name: Update Perms
        shell: bash
        run: |
          echo ${{ secrets.SUDO_PASS }} | sudo -S chmod -R 776 ../Sudoku

      - name: Setting Ownership
        shell: bash
        run: |
          echo ${{ secrets.SUDO_PASS }} | sudo -S chown -R connor:connor ../Sudoku

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Create Properties File
        id: create_prop_file
        shell: bash
        run: |
          echo "sdk.dir=/home/connor/Android/Sdk" >> local.properties

      - name: Update gradlew Perms
        shell: bash
        run: |
          echo ${{ secrets.SUDO_PASS }} | sudo -S echo chmod 766 gradlew

      - name: Run Unit Tests
        shell: bash
        run: |
          echo ${{ secrets.SUDO_PASS }} | sudo -S ./gradlew test
        continue-on-error: true

      - name: Run Instrument Tests
        shell: bash
        run: |
          echo ${{ secrets.SUDO_PASS }} | sudo -S ./gradlew connectedAndroidTest
        continue-on-error: true

      - name: Convert Results
        shell: bash
        run: |
          python3 ./Scripts/GenerateResults.py "/home/connor/Documents/Runners/Sudoku/_work/Sudoku/Sudoku/app/build/test-results/testDebugUnitTest/TEST-com.example.sudoku.SudokuTest.xml" "/home/connor/Documents/Runners/Sudoku/_work/Sudoku/Sudoku/app/build/outputs/androidTest-results/connected/debug/TEST-Pixel_9_Pro_API_35(AVD) - 15-_app-.xml"

      - name: Publish Results
        if: success()
        run: |
          npx ctrf merge "/home/connor/Documents/SudokuResults/"
          npx github-actions-ctrf "/home/connor/Documents/SudokuResults/results.json"

      - name: Clean up
        if: steps.create_prop_file.outcome == 'success'
        shell: bash
        run: |
          echo ${{ secrets.SUDO_PASS }} | sudo -S rm local.properties